version: "3"
services:
  web:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    ports:
      - 5000:5000
    command: bash -c "flask db upgrade && flask run --host=0.0.0.0"
    environment:
      - FLASK_ENV=development

  # TODO get rid of Flask-Celery per http://flask.pocoo.org/docs/1.0/patterns/celery/
  #celery:
  #  restart: unless-stopped
  #  build:
  #    context: .
  #  volumes:
  #    - .:/app
  #  depends_on:
  #    - mysql
  #    - redis
  #  command: bash -c "python3 manage.py celery_worker"
  gulp:
    image: node:10-alpine
    command: npm run build
    volumes:
      - .:/app
    working_dir: /app

  mysql:
    image: mariadb:10.3
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=devel
      - MYSQL_PASSWORD=devel
      - MYSQL_DATABASE=devel

  redis:
    image: redis:5.0-alpine
