version: "3"
services:
  web:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - smtp
    ports:
      - 5000:5000
    command: bash -c "flask db upgrade && flask run --host=0.0.0.0"
    environment:
      - FLASK_ENV=development

  gulp:
    image: node:10-alpine
    command: npm run build
    volumes:
      - .:/app
    working_dir: /app

  postgres:
    image: postgres:11.2
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: sensorsafrica-ssrp
      POSTGRES_PASSWORD: sensorsafrica-ssrp
      POSTGRES_DB: sensorsafrica-ssrp
  
  redis:
    image: "redis:5.0.4"
    ports:
      - "6379:6379"

  smtp:
    image: tianon/exim4
